apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: embarkx/hello-python:latest
          # env:
          #   - name: app-massage
          #     value: "hello from app.yaml"
          #   - name: db_password
          #     value: "12345678" # Database password
          env:
            - name: ENV_VALUE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_MESSAGE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 3000
